name: deploy

on:
  push:
    branches:
      - test


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: github-deployment
      
      - name: Git Pull
        run: |
          git pull origin test --ff --allow-unrelated-histories
          git push

      - run: npm i
      - run: |
          git config --global user.email "harshad.bhosale@cogoport.com"
          git config --global user.name "HarshadBhosale"
          git remote set-url origin https://HarshadBhosale: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@github.com/HarshadBhosale/finance_tracker_frontend
          npm run deploy
        env:
          CI: false