name: deploy

on:
  push:
    branches:
      - test


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: test

      - run: npm i
      - run: git config --global user.email "harshad.bhosale@cogoport.com"
      - run: git config --global user.name "HarshadBhosale"
      - run: git remote set-url origin https://${{ secrets.PAT }}@github.com/HarshadBhosale/finance_tracker_frontend.git
      - run: npm run deploy
        env:
          CI: false
  