name: deploy

on:
  push:
    branches:
      - test


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      
      - name: Check out code
        uses: actions/checkout@v3
        with:
          ref: github-deployment
      
      - name: Git Pull
        run: |
          git pull origin test --ff --allow-unrelated-histories
          git push

      - run: npm i
      - run: |
          git config --global user.email "harshad.bhosale@cogoport.com"
          git config --global user.name "HarshadBhosale"
          mkdir ~/.ssh
          echo ${{ secrets.PUBLIC_KEY }} >> ~/.ssh/id_ed25519.pub
          echo ${{ secrets.PRIVATE_KEY }} >> ~/.ssh/id_ed25519
          npm run deploy
        env:
          CI: false