name: deploy

on:
  push:
    branches:
      - test


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-20.04
    steps:
      - name: Debug
        uses: hmarr/debug-action@v2
      
      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: github-deployment
      
      - name: Git Pull
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull origin test --ff
          git commit -m "Merge branch 'test' of github.com:HarshadBhosale/finance_tracker_frontend into github-deployment"
          git push

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - run: npm ci
      - run: npm run deploy